type Platform {
  id: Id
  name: String!
  igdbId: Int
  logo: PlatformLogo
  igdbGameList: [String]
  games: [Game]
}

type PlatformLogo {
  url: String
  cloudinaryid: String
  width: Int
  height: Int
}
