type User {
  id: Int
  email: String
  username: String
  firstName: String
  lastName: String
  createdAt: String
  updatedAt: String
  token: String
  collection: Collection
}

input NewUserInput {
  email: String
  username: String
  firstName: String
  lastName: String
  password: String
}
