type Collection {
  id: Int
  owner: String
  items: [GameCollectionItem]
}

type GameCollectionItem {
  id: Int
  game: Game
  platform: Platform
  note: CollectionItemNote
  borrowed: Boolean
  borrowedDate: String
  cost: Float
  details: CollectionItemDetails
}

type CollectionItemNote {
  text: String
  isPrivate: Boolean
}

type CollectionItemDetails {
  hasCartDiskItem: Boolean
  hasCaseBox: Boolean
  hasManual: Boolean
  hasOtherInserts: Boolean
}
